# ETL Processes
Use this notebook to develop the ETL process for each of your tables before completing the `etl.py` file to load the whole datasets.

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [1]:
import os
import glob
import psycopg2
import pandas as pd
from sql_queries import *

In [35]:
conn.close() 

In [3]:
conn = psycopg2.connect("host=127.0.0.1 dbname=sparkifydb2 user=postgres password=datapassword")
cur = conn.cursor()

In [4]:
def get_files(filepath):
    all_files = []
    for root, dirs, files in os.walk(filepath):
        files = glob.glob(os.path.join(root,'*.json'))
        for f in files :
            all_files.append(os.path.abspath(f))
    
    return all_files

In [5]:
# Preview list of  json files
get_files("data/song_data")

['C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAAAW128F429D538.json',
 'C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAABD128F429CF47.json',
 'C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAADZ128F9348C2E.json',
 'C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAAEF128F4273421.json',
 'C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAAFD128F92F423A.json',
 'C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAAMO128F1481E7F.json',
 'C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAAMQ128F1460CD3.json',
 'C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAAPK128E0786D96.json',
 'C:\\Users\\randy\\Desktop\\Postgres-DataModeling-Project\\data\\song_data\\A\\A\\A\\TRAAARJ128F9320760

# Process `song_data`
In this first part, you'll perform ETL on the first dataset, `song_data`, to create the `songs` and `artists` dimensional tables.

Let's perform ETL on a single song file and load a single record into each table to start.
- Use the `get_files` function provided above to get a list of all song JSON files in `data/song_data`
- Select the first song in this list
- Read the song file and view the data

In [6]:
song_files = get_files("data/song_data")

In [7]:
filepath = song_files[0]

In [8]:
df = pd.read_json(filepath, lines=True)
df.head()

num_songs           artist_id  artist_latitude  artist_longitude  \
0          1  ARD7TVE1187B99BFB1              NaN               NaN   

   artist_location artist_name             song_id             title  \
0  California - LA      Casual  SOMZWCG12A8C13C480  I Didn't Mean To   

    duration  year  
0  218.93179     0

In [9]:
# check column types
df.dtypes

num_songs             int64
artist_id            object
artist_latitude     float64
artist_longitude    float64
artist_location      object
artist_name          object
song_id              object
title                object
duration            float64
year                  int64
dtype: object

## #1: `songs` Table
#### Extract Data for Songs Table
- Select columns for song ID, title, artist ID, year, and duration
- Use `df.values` to select just the values from the dataframe
- Index to select the first (only) record in the dataframe
- Convert the array to a list and set it to `song_data`

In [10]:
song_data = list(df[['song_id', 'title', 'artist_id', 'year', 'duration']].values[0])
song_data

['SOMZWCG12A8C13C480', "I Didn't Mean To", 'ARD7TVE1187B99BFB1', 0, 218.93179]

#### Insert Record into Song Table
Implement the `song_table_insert` query in `sql_queries.py` and run the cell below to insert a record for this song into the `songs` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `songs` table in the sparkify database.

In [11]:
cur.execute(song_table_insert, song_data)
conn.commit()

In [12]:
# checking if record was added successfully
try: 
    cur.execute("SELECT * FROM songs;")
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

row = cur.fetchone()
while row:
   print(row)
   row = cur.fetchone()

('SOMZWCG12A8C13C480', "I Didn't Mean To", 'ARD7TVE1187B99BFB1', 0, 218.93179)


Run `test.ipynb` to see if you've successfully added a record to this table.

## #2: `artists` Table
#### Extract Data for Artists Table
- Select columns for artist ID, name, location, latitude, and longitude
- Use `df.values` to select just the values from the dataframe
- Index to select the first (only) record in the dataframe
- Convert the array to a list and set it to `artist_data`

In [13]:
df

num_songs           artist_id  artist_latitude  artist_longitude  \
0          1  ARD7TVE1187B99BFB1              NaN               NaN   

   artist_location artist_name             song_id             title  \
0  California - LA      Casual  SOMZWCG12A8C13C480  I Didn't Mean To   

    duration  year  
0  218.93179     0

In [14]:
artist_data = list(df[['artist_id', 'artist_name', 'artist_location', 'artist_latitude', 'artist_longitude']].values[0])
artist_data

['ARD7TVE1187B99BFB1', 'Casual', 'California - LA', nan, nan]

#### Insert Record into Artist Table
Implement the `artist_table_insert` query in `sql_queries.py` and run the cell below to insert a record for this song's artist into the `artists` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `artists` table in the sparkify database.

In [15]:
cur.execute(artist_table_insert, artist_data)
conn.commit()

In [16]:
# checking if record was added successfully
try: 
    cur.execute("SELECT * FROM artists;")
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

row = cur.fetchone()
while row:
   print(row)
   row = cur.fetchone()

('ARD7TVE1187B99BFB1', 'Casual', 'California - LA', nan, nan)


Run `test.ipynb` to see if you've successfully added a record to this table.

# Process `log_data`
In this part, you'll perform ETL on the second dataset, `log_data`, to create the `time` and `users` dimensional tables, as well as the `songplays` fact table.

Let's perform ETL on a single log file and load a single record into each table.
- Use the `get_files` function provided above to get a list of all log JSON files in `data/log_data`
- Select the first log file in this list
- Read the log file and view the data

In [17]:
log_files = get_files("data/log_data")

In [18]:
filepath = log_files[0]

In [19]:
df = pd.read_json(filepath, lines=True)
df.head()

artist       auth firstName gender  itemInSession lastName     length  \
0     None  Logged In    Walter      M              0     Frye        NaN   
1     None  Logged In    Kaylee      F              0  Summers        NaN   
2  Des'ree  Logged In    Kaylee      F              1  Summers  246.30812   
3     None  Logged In    Kaylee      F              2  Summers        NaN   
4  Mr Oizo  Logged In    Kaylee      F              3  Summers  144.03873   

  level                           location method      page   registration  \
0  free  San Francisco-Oakland-Hayward, CA    GET      Home  1540919166796   
1  free        Phoenix-Mesa-Scottsdale, AZ    GET      Home  1540344794796   
2  free        Phoenix-Mesa-Scottsdale, AZ    PUT  NextSong  1540344794796   
3  free        Phoenix-Mesa-Scottsdale, AZ    GET   Upgrade  1540344794796   
4  free        Phoenix-Mesa-Scottsdale, AZ    PUT  NextSong  1540344794796   

   sessionId          song  status             ts  \
0         38          None     200  1541105830796   
1        139          None     200  1541106106796   
2        139  You Gotta Be     200  1541106106796   
3        139          None     200  1541106132796   
4        139       Flat 55     200  1541106352796   

                                           userAgent  userId  
0  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...      39  
1  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8  
2  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8  
3  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8  
4  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8

## #3: `time` Table
#### Extract Data for Time Table
- Filter records by `NextSong` action
- Convert the `ts` timestamp column to datetime
  - Hint: the current timestamp is in milliseconds
- Extract the timestamp, hour, day, week of year, month, year, and weekday from the `ts` column and set `time_data` to a list containing these values in order
  - Hint: use pandas' [`dt` attribute](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.html) to access easily datetimelike properties.
- Specify labels for these columns and set to `column_labels`
- Create a dataframe, `time_df,` containing the time data for this file by combining `column_labels` and `time_data` into a dictionary and converting this into a dataframe

In [20]:
# Filter records by NextSong action
df = df.loc[df['page'] == 'NextSong']
df.head()

artist       auth firstName gender  itemInSession lastName  \
2            Des'ree  Logged In    Kaylee      F              1  Summers   
4            Mr Oizo  Logged In    Kaylee      F              3  Summers   
5         Tamba Trio  Logged In    Kaylee      F              4  Summers   
6     The Mars Volta  Logged In    Kaylee      F              5  Summers   
7  Infected Mushroom  Logged In    Kaylee      F              6  Summers   

      length level                     location method      page  \
2  246.30812  free  Phoenix-Mesa-Scottsdale, AZ    PUT  NextSong   
4  144.03873  free  Phoenix-Mesa-Scottsdale, AZ    PUT  NextSong   
5  177.18812  free  Phoenix-Mesa-Scottsdale, AZ    PUT  NextSong   
6  380.42077  free  Phoenix-Mesa-Scottsdale, AZ    PUT  NextSong   
7  440.26730  free  Phoenix-Mesa-Scottsdale, AZ    PUT  NextSong   

    registration  sessionId                          song  status  \
2  1540344794796        139                  You Gotta Be     200   
4  1540344794796        139                       Flat 55     200   
5  1540344794796        139  Quem Quiser Encontrar O Amor     200   
6  1540344794796        139                     Eriatarka     200   
7  1540344794796        139               Becoming Insane     200   

              ts                                          userAgent  userId  
2  1541106106796  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8  
4  1541106352796  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8  
5  1541106496796  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8  
6  1541106673796  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8  
7  1541107053796  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8

In [21]:
# Convert the ts timestamp column to datetime
t = pd.to_datetime(df['ts'], unit='ms')
t.head()

2   2018-11-01 21:01:46.796
4   2018-11-01 21:05:52.796
5   2018-11-01 21:08:16.796
6   2018-11-01 21:11:13.796
7   2018-11-01 21:17:33.796
Name: ts, dtype: datetime64[ns]

In [22]:
time_data = [df.ts.values, t.dt.hour.values, t.dt.day.values, t.dt.isocalendar().week.values, t.dt.month.values, t.dt.year.values, t.dt.weekday.values]
column_labels = ['start_time', 'hour', 'day', 'week', 'month', 'year', 'weekday']
time_data

[array([1541106106796, 1541106352796, 1541106496796, 1541106673796,
        1541107053796, 1541107493796, 1541107734796, 1541108520796,
        1541109125796, 1541109325796, 1541110994796], dtype=int64),
 array([21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 <IntegerArray>
 [44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44]
 Length: 11, dtype: UInt32,
 array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11], dtype=int64),
 array([2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018],
       dtype=int64),
 array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)]

In [23]:
time_df = pd.DataFrame(dict(zip(column_labels, time_data)))
time_df.tail(5)

start_time  hour  day  week  month  year  weekday
6   1541107734796    21    1    44     11  2018        3
7   1541108520796    21    1    44     11  2018        3
8   1541109125796    21    1    44     11  2018        3
9   1541109325796    21    1    44     11  2018        3
10  1541110994796    22    1    44     11  2018        3

In [24]:
time_df.dtypes

start_time     int64
hour           int64
day            int64
week          UInt32
month          int64
year           int64
weekday        int64
dtype: object

In [25]:
import numpy as np
time_df.week = time_df.week.astype(np.int64)

#### Insert Records into Time Table
Implement the `time_table_insert` query in `sql_queries.py` and run the cell below to insert records for the timestamps in this log file into the `time` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `time` table in the sparkify database.

In [26]:
for i, row in time_df.iterrows():
    cur.execute(time_table_insert, list(row))
    conn.commit()

In [27]:
# checking if record was added successfully
try: 
    cur.execute("SELECT * FROM time;") 
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

row = cur.fetchone()
while row:
   print(row)
   row = cur.fetchone()

(1541106106796, 21, 1, 44, 11, 2018, 3)
(1541106352796, 21, 1, 44, 11, 2018, 3)
(1541106496796, 21, 1, 44, 11, 2018, 3)
(1541106673796, 21, 1, 44, 11, 2018, 3)
(1541107053796, 21, 1, 44, 11, 2018, 3)
(1541107493796, 21, 1, 44, 11, 2018, 3)
(1541107734796, 21, 1, 44, 11, 2018, 3)
(1541108520796, 21, 1, 44, 11, 2018, 3)
(1541109125796, 21, 1, 44, 11, 2018, 3)
(1541109325796, 21, 1, 44, 11, 2018, 3)
(1541110994796, 22, 1, 44, 11, 2018, 3)


Run `test.ipynb` to see if you've successfully added records to this table.

## #4: `users` Table
#### Extract Data for Users Table
- Select columns for user ID, first name, last name, gender and level and set to `user_df`

In [28]:
user_df = df[['userId', 'firstName', 'lastName', 'gender', 'level']]
user_df.tail(5)

userId firstName lastName gender level
9        8    Kaylee  Summers      F  free
10      10    Sylvie     Cruz      F  free
12      26      Ryan    Smith      M  free
13      26      Ryan    Smith      M  free
14     101    Jayden      Fox      M  free

#### Insert Records into Users Table
Implement the `user_table_insert` query in `sql_queries.py` and run the cell below to insert records for the users in this log file into the `users` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `users` table in the sparkify database.

In [29]:
for i, row in user_df.iterrows():
    cur.execute(user_table_insert, row)
    conn.commit()

In [30]:
# checking if record was added successfully
try: 
    cur.execute("SELECT * FROM users;") 
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

row = cur.fetchone()
while row:
   print(row)
   row = cur.fetchone()

(8, 'Kaylee', 'Summers', 'F', 'free')
(10, 'Sylvie', 'Cruz', 'F', 'free')
(26, 'Ryan', 'Smith', 'M', 'free')
(101, 'Jayden', 'Fox', 'M', 'free')


Run `test.ipynb` to see if you've successfully added records to this table.

## #5: `songplays` Table
#### Extract Data and Songplays Table
This one is a little more complicated since information from the songs table, artists table, and original log file are all needed for the `songplays` table. Since the log file does not specify an ID for either the song or the artist, you'll need to get the song ID and artist ID by querying the songs and artists tables to find matches based on song title, artist name, and song duration time.
- Implement the `song_select` query in `sql_queries.py` to find the song ID and artist ID based on the title, artist name, and duration of a song.
- Select the timestamp, user ID, level, song ID, artist ID, session ID, location, and user agent and set to `songplay_data`

#### Insert Records into Songplays Table
- Implement the `songplay_table_insert` query and run the cell below to insert records for the songplay actions in this log file into the `songplays` table. Remember to run `create_tables.py` before running the cell below to ensure you've created/resetted the `songplays` table in the sparkify database.

In [31]:
df.tail()

artist       auth firstName gender  itemInSession lastName  \
9         Girl Talk  Logged In    Kaylee      F              8  Summers   
10  Black Eyed Peas  Logged In    Sylvie      F              0     Cruz   
12     Fall Out Boy  Logged In      Ryan      M              1    Smith   
13           M.I.A.  Logged In      Ryan      M              2    Smith   
14         Survivor  Logged In    Jayden      M              0      Fox   

       length level                                      location method  \
9   160.15628  free                   Phoenix-Mesa-Scottsdale, AZ    PUT   
10  214.93506  free  Washington-Arlington-Alexandria, DC-VA-MD-WV    PUT   
12  200.72444  free            San Jose-Sunnyvale-Santa Clara, CA    PUT   
13  233.71710  free            San Jose-Sunnyvale-Santa Clara, CA    PUT   
14  245.36771  free                      New Orleans-Metairie, LA    PUT   

        page   registration  sessionId  \
9   NextSong  1540344794796        139   
10  NextSong  1540266185796          9   
12  NextSong  1541016707796        169   
13  NextSong  1541016707796        169   
14  NextSong  1541033612796        100   

                                                song  status             ts  \
9                                         Once again     200  1541107734796   
10                                           Pump It     200  1541108520796   
12                    Nobody Puts Baby In The Corner     200  1541109125796   
13  Mango Pickle Down River (With The Wilcannia Mob)     200  1541109325796   
14                                  Eye Of The Tiger     200  1541110994796   

                                            userAgent  userId  
9   "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       8  
10  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...      10  
12  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...      26  
13  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...      26  
14  "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...     101

In [32]:
for index, row in df.iterrows():

    # get songid and artistid from song and artist tables
    cur.execute(song_select, (row.song, row.artist, row.length))
    results = cur.fetchone()
    
    if results:
        songid, artistid = results
    else:
        songid, artistid = None, None

    # insert songplay record
    songplay_data = [row.ts, row.userId, row.level, songid, artistid, row.sessionId, row.location, row.userAgent]
    cur.execute(songplay_table_insert, songplay_data)
    conn.commit()

In [33]:
# checking if record was added successfully
try: 
    cur.execute("SELECT * FROM songplays;") 
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

row = cur.fetchone()
while row:
   print(row)
   row = cur.fetchone()

(1, 1541106106796, 8, 'free', None, None, 139, 'Phoenix-Mesa-Scottsdale, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"')
(2, 1541106352796, 8, 'free', None, None, 139, 'Phoenix-Mesa-Scottsdale, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"')
(3, 1541106496796, 8, 'free', None, None, 139, 'Phoenix-Mesa-Scottsdale, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"')
(4, 1541106673796, 8, 'free', None, None, 139, 'Phoenix-Mesa-Scottsdale, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"')
(5, 1541107053796, 8, 'free', None, None, 139, 'Phoenix-Mesa-Scottsdale, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"')
(6, 1541107493796, 8, 'free', None,

Run `test.ipynb` to see if you've successfully added records to this table.

# Close Connection to Sparkify Database

In [34]:
conn.close()

# Implement `etl.py`
Use what you've completed in this notebook to implement `etl.py`.